name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: dotnet restore Source\\MQTTnet.App.sln

      - name: Build win-x86
        run: dotnet publish Source\\MQTTnet.App\\MQTTnet.App.csproj -r win-x86 -p:Configuration=Release -p:PublishSingleFile=true -p:PublishReadyToRun=false --self-contained true

      - name: Collect win-x86 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MQTTnet.App-win-x86
          path: /home/runner/work/MQTTnet.App/MQTTnet.App/Source/MQTTnet.App/bin/Release/net6.0/win-x86/publish/

      - name: Build win-x64
        run: dotnet publish Source\\MQTTnet.App\\MQTTnet.App.csproj -r win-x64 -p:Configuration=Release -p:PublishSingleFile=true -p:PublishReadyToRun=false --self-contained true

      - name: Collect win-x64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MQTTnet.App-win-x64
          path: /home/runner/work/MQTTnet.App/MQTTnet.App/Source/MQTTnet.App/bin/Release/net6.0/win-x64/publish/

      - name: Build win-arm
        run: dotnet publish Source\\MQTTnet.App\\MQTTnet.App.csproj -r win-arm -p:Configuration=Release -p:PublishSingleFile=true -p:PublishReadyToRun=false --self-contained true

      - name: Collect win-arm artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MQTTnet.App-win-arm
          path: /home/runner/work/MQTTnet.App/MQTTnet.App/Source/MQTTnet.App/bin/Release/net6.0/win-arm/publish/

      - name: Build win-arm64
        run: dotnet publish Source\\MQTTnet.App\\MQTTnet.App.csproj -r win-arm64 -p:Configuration=Release -p:PublishSingleFile=true -p:PublishReadyToRun=false --self-contained true

      - name: Collect win-arm64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MQTTnet.App-win-arm64
          path: /home/runner/work/MQTTnet.App/MQTTnet.App/Source/MQTTnet.App/bin/Release/net6.0/win-arm64/publish/

      - name: Build osx-x64
        run: dotnet publish Source\\MQTTnet.App\\MQTTnet.App.csproj -r osx-x64 -p:Configuration=Release -p:PublishSingleFile=true -p:PublishReadyToRun=false --self-contained true

      - name: Collect osx-x64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MQTTnet.App-osx-x64
          path: /home/runner/work/MQTTnet.App/MQTTnet.App/Source/MQTTnet.App/bin/Release/net6.0/osx-x64/publish/

      - name: Build linux-x86
        run: dotnet publish Source\\MQTTnet.App\\MQTTnet.App.csproj -r linux-x86 -p:Configuration=Release -p:PublishSingleFile=true -p:PublishReadyToRun=false --self-contained true

      - name: Collect linux-x86 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MQTTnet.App-linux-x86
          path: /home/runner/work/MQTTnet.App/MQTTnet.App/Source/MQTTnet.App/bin/Release/net6.0/linux-x86/publish/

      - name: Build linux-x64
        run: dotnet publish Source\\MQTTnet.App\\MQTTnet.App.csproj -r linux-x64 -p:Configuration=Release -p:PublishSingleFile=true -p:PublishReadyToRun=false --self-contained true

      - name: Collect linux-x64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MQTTnet.App-linux-x64
          path: /home/runner/work/MQTTnet.App/MQTTnet.App/Source/MQTTnet.App/bin/Release/net6.0/linux-x64/publish/

      - name: Build linux-arm
        run: dotnet publish Source\\MQTTnet.App\\MQTTnet.App.csproj -r linux-arm -p:Configuration=Release -p:PublishSingleFile=true -p:PublishReadyToRun=false --self-contained true

      - name: Collect linux-arm artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MQTTnet.App-linux-arm
          path: /home/runner/work/MQTTnet.App/MQTTnet.App/Source/MQTTnet.App/bin/Release/net6.0/linux-arm/publish/

      - name: Build linux-arm64
        run: dotnet publish Source\\MQTTnet.App\\MQTTnet.App.csproj -r linux-arm64 -p:Configuration=Release -p:PublishSingleFile=true -p:PublishReadyToRun=false --self-contained true

      - name: Collect linux-arm artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MQTTnet.App-linux-arm64
          path: /home/runner/work/MQTTnet.App/MQTTnet.App/Source/MQTTnet.App/bin/Release/net6.0/linux-arm64/publish/